# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'managed': False},
        ),
    ]
